worker_processes auto;

events {
    worker_connections 1024;
}

http {

    include mime.types;
    sendfile on;

    limit_req_zone $binary_remote_addr zone=api:10m rate=10r/m;
    limit_req_zone $binary_remote_addr zone=hls:10m rate=30r/s;

    server {
        listen 80;
        server_name ${STREAM_DOMAIN};

        # API
        location /api/ {
            limit_req zone=api burst=10 nodelay;

            proxy_pass http://api:8000/;

            add_header Access-Control-Allow-Origin $http_origin always;
            add_header Access-Control-Allow-Methods "GET, OPTIONS" always;
            add_header Access-Control-Allow-Headers "*" always;
        }

        # HLS
        location /hls/ {
            limit_req zone=hls burst=50;

            secure_link $arg_token,$arg_expires;
            secure_link_md5 "${STREAM_SECRET}$secure_link_expires";

            # Bad Signature
            if ($secure_link = "") {
                return 403;
            }

            # Expired
            if ($secure_link = "0") {
                return 403;
            }

            proxy_pass http://wireguard:8888/;

            add_header Access-Control-Allow-Origin *;
        }
    }
}