networks:
  wgnet:
    driver: bridge

services:
  wireguard:
    image: linuxserver/wireguard
    container_name: wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - TZ=Europe/London
    volumes:
      - ./wg0.conf:/config/wg_confs/wg0.conf
    ports:
      - "8554:8554"
    networks:
      - wgnet
    restart: unless-stopped

  mediamtx:
    image: bluenviron/mediamtx:latest
    container_name: mediamtx
    network_mode: "service:wireguard"
    volumes:
      - ./mediamtx.yml:/mediamtx.yml
    restart: unless-stopped
    depends_on:
      - wireguard
