worker_processes auto;

events {
    worker_connections 1024;
}

http {

    include mime.types;
    sendfile on;

    limit_req_zone $binary_remote_addr zone=api:10m rate=10r/m;
    limit_req_zone $binary_remote_addr zone=hls:10m rate=30r/s;

    map $http_client_id $api_authorized {
        default 0;
        "${API_AUTH_HEADER_SECRET}" 1;
    }

    server {
        listen 80;
        server_name ${STREAM_DOMAIN};

        location / {
            return 403;
        }

        location /api/ {
            limit_req zone=api burst=10 nodelay;

            add_header Access-Control-Allow-Origin $http_origin always;
            add_header Access-Control-Allow-Methods "GET, OPTIONS" always;
            add_header Access-Control-Allow-Headers "*" always;
            add_header Access-Control-Max-Age 86400 always;

            # Let browser CORS preflight pass without API auth header.
            if ($request_method = OPTIONS) { 
                return 204;
            }

            if ($api_authorized = 0) {
                return 401 '{"message": "go away you weasel"}';
            }

            proxy_pass http://api:8000/;
        }

        location /thumbs/ {
            limit_req zone=api burst=10 nodelay;

            add_header Access-Control-Allow-Origin $http_origin always;
            add_header Access-Control-Allow-Methods "GET, OPTIONS" always;
            add_header Access-Control-Allow-Headers "*" always;
            add_header Access-Control-Max-Age 86400 always;

            secure_link $arg_token,$arg_expires;
            secure_link_md5 "${STREAM_SECRET}$secure_link_expires";

            # Bad Signature
            if ($secure_link = "") {
                return 401;
            }

            # Expired
            if ($secure_link = "0") {
                return 401;
            }

            alias /thumbs/;
        }

        location /hls/ {
            limit_req zone=hls burst=50;

            add_header Access-Control-Allow-Origin *;

            secure_link $arg_token,$arg_expires;
            secure_link_md5 "${STREAM_SECRET}$secure_link_expires";

            # Bad Signature
            if ($secure_link = "") {
                return 401;
            }

            # Expired
            if ($secure_link = "0") {
                return 401;
            }

            proxy_hide_header Access-Control-Allow-Origin;
            proxy_set_header X-Forwarded-For $remote_addr;
            proxy_pass http://wireguard:8888/;
        }
    }
}